FROM node:15

WORKDIR /app

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

# cache node_modules
COPY package.json package.json
COPY yarn.lock yarn.lock

COPY desktop/main-app/package.json desktop/main-app/package.json
COPY desktop/renderer-app/package.json desktop/renderer-app/package.json

COPY packages/flat-components/package.json packages/flat-components/package.json
COPY packages/flat-i18n/package.json packages/flat-i18n/package.json
COPY packages/flat-types/package.json packages/flat-types/package.json

COPY web/flat-web/package.json web/flat-web/package.json

RUN sed -i "s/.*preinstall.*//g" package.json && sed -i "s/.*desktop.*//g" package.json && yarn install --frozen-lockfile
