name: Deploy Flat Web Dev
on:
  push:
    branches:
      - "main"
    paths:
      - "config/**"
      - "web/flat-web/**"
      - "packages/flat-components/src/**"
      - "packages/flat-i18n/locales/**"
      - "packages/flat-types/src/**"
      - ".github/workflows/deploy-web-dev.yml"

jobs:
  deploy-flat-web-dev:
    environment: development

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          node ./scripts/ci/remove-workspace-packages.js web
          node ./scripts/ci/remove-package-scripts-hooks.js
          # failure automatically retries 3 times
          yarn run bootstrap || yarn run bootstrap || yarn run bootstrap

      - name: Build flat web development
        run: yarn workspace flat-web build -m development

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Reset dockerignore
        run: |
          echo "*" > .dockerignore
          echo "!web/flat-web/dist" >> .dockerignore
          echo "!web/flat-web/deploy/nginx" >> .dockerignore

      - name: Build and push images
        env:
          COMMIT_SHA_TAG: development-${{ github.sha }}
          LATEST_DEV_TAG: dev-latest
          PRIVATE_DOCKERHUB_REGISTRY: ${{ secrets.PRIVATE_DOCKERHUB_REGISTRY }}
          PRIVATE_DOCKERHUB_USERNAME: ${{ secrets.PRIVATE_DOCKERHUB_USERNAME }}
          PRIVATE_DOCKERHUB_PASSWORD: ${{ secrets.PRIVATE_DOCKERHUB_PASSWORD }}
        run: |
          docker build . -f web/flat-web/deploy/Dockerfile -t agoraflat/flat-web:$COMMIT_SHA_TAG -t agoraflat/flat-web:$LATEST_DEV_TAG -t $PRIVATE_DOCKERHUB_REGISTRY/agoraflat/flat-web:$COMMIT_SHA_TAG -t $PRIVATE_DOCKERHUB_REGISTRY/agoraflat/flat-web:$LATEST_DEV_TAG
          docker push agoraflat/flat-web:$COMMIT_SHA_TAG
          docker push agoraflat/flat-web:$LATEST_DEV_TAG

          docker login -u $PRIVATE_DOCKERHUB_USERNAME -p $PRIVATE_DOCKERHUB_PASSWORD $PRIVATE_DOCKERHUB_REGISTRY
          docker push $PRIVATE_DOCKERHUB_REGISTRY/agoraflat/flat-web:$COMMIT_SHA_TAG
          docker push $PRIVATE_DOCKERHUB_REGISTRY/agoraflat/flat-web:$LATEST_DEV_TAG

      - name: Prep helm chart
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.PRIVATE_DOCKERHUB_REGISTRY }}/agoraflat/flat-web
          DOCKER_IMAGE_TAG: $COMMIT_SHA_TAG
        run: |
          export APPVERSION=development-${{ github.sha }}
          export CHART=./web/flat-web/helm/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: $APPVERSION/" $CHART

          export Value=./web/flat-web/helm/values.yaml
          sed -i "s/DOCKER_IMAGE_NAME/$DOCKER_IMAGE_NAME/" $Value
          sed -i "s/DOCKER_IMAGE_TAG/$DOCKER_IMAGE_TAG/" $Value

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade flat-web ./web/flat-web/helm --install --wait --atomic --namespace=default
          kubeconfig: '${{ secrets.KUBECONFIG }}'
