name: flat-web Docker Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".yarnrc"
      - "LICENSE"
      - "desktop"

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt secret to envfile
        env:
          GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
          GPG_SECRET_FILE: ${{ secrets.GPG_SECRET_FILE }}
        run: echo $GPG_SECRET_FILE | base64 -d | gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSWORD" --output config/.env.${{ env.BUILD_ENV }}.local

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flat-web:${{ env.BUILD_ENV }}-${{ github.ref }}
          file: deploy/Dockerfile
          build-args: build_env=${{ env.BUILD_ENV }}
